#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  gen-firewall-fixtures.sh — regenerate tests/fixtures/firewall/* from the
#  REAL `apex-firewall` helper in an apex-os checkout (roadmap P1-044/P2-006).
#
#  ── WHY THIS FILE EXISTS ────────────────────────────────────────────────────
#
#  Every firewall payload the shell's suite checks against used to live inline
#  in tests/firewall-test.js under a header saying it was CAPTURED. It was. But
#  nothing re-captured it, and a fixture nothing re-captures stops being a
#  record of the machine and becomes a record of the machine on the day
#  somebody ran the command. Two of them had already drifted by 2026-09-14:
#
#    * STATUS_LOADED was captured before apex-os `c7a28f2c` put the shared-links
#      block into the status screen. With the policy loaded the helper now
#      prints two more lines, between the "always allowed" heading and the
#      "exceptions you have added" heading — and the shell's parser assigned
#      them to alwaysAllowed, so the settings page reported "DHCP and DNS are
#      open on those links only" as the list of traffic the firewall never
#      drops. The suite stayed green: it was checking a shape the tool could no
#      longer print.
#
#    * LIST was captured with eleven services. The shipped catalogue
#      (files/system/firewall/services) has had twelve since `apex-remote
#      tcp 7717` was added. The suite asserted the count was eleven, so it was
#      asserting the catalogue of an older image.
#
#  So the fixtures are FILES now, generated by this script, and `--check`
#  re-captures into a temporary directory and diffs. Drift is a failing command
#  rather than a green suite.
#
#  ── WHAT --check CAN AND CANNOT BE ──────────────────────────────────────────
#
#  It needs BOTH repositories, so it cannot run in apex-shell's CI, which
#  checks out apex-shell alone. Stated plainly rather than hidden behind a
#  skip: this is a gate for a machine that has both trees — a developer's, or
#  the integrator's — and it is not a pipeline step.
#
#  What defends the user's machine is not this script. It is
#  src/services/firewall.js validating the SHAPE of `apex firewall status
#  --json` and answering "could not be read" when it does not match, instead of
#  rendering whatever a prose line happened to land on. Drift is loud there.
#  This script is how the fixtures stop being stale between now and then.
#
#  ── USAGE ───────────────────────────────────────────────────────────────────
#
#      tests/fixtures/firewall/gen-firewall-fixtures.sh [--check] [APEX_OS_DIR]
#      APEX_OS=/path/to/apex-os tests/fixtures/firewall/gen-firewall-fixtures.sh
#
#  ── WHY A COPY OF THE HELPER ────────────────────────────────────────────────
#
#  CONF_DIR is a readonly constant naming the live machine's
#  /etc/apex/firewall.d. This runs on a developer's laptop and must never write
#  exception files there, so the fixtures go in a temporary directory and the
#  helper that is driven is a COPY whose one constant is redirected.
#
#  A copy fails in one specific way: if the substitution matches nothing the
#  copy is identical to its source and every capture below silently becomes a
#  capture of whatever happens to be in the live machine's exception directory.
#  So the redirect is asserted, as a hard failure and not a skip — the same
#  guard apex-os's tests/test-apex-firewall.sh puts on the same copy.
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

check=0
osdir=""
for a in "$@"; do
    case "$a" in
        --check) check=1 ;;
        *)       osdir="$a" ;;
    esac
done
[ -n "$osdir" ] || osdir="${APEX_OS:-}"
if [ -z "$osdir" ]; then
    # Siblings and the canonical checkout only. A scratch worktree path was
    # listed here once and taken straight back out: a stale tree sitting at a
    # remembered path is a SOURCE that has drifted, and capturing from it
    # without being asked is precisely the failure this script exists to stop.
    for c in "$here/../../../../apex-os" "$here/../../../../../apex/apex-os" \
             "$HOME/Projects/apex/apex-os"; do
        [ -r "$c/files/system/libexec/apex-firewall" ] && osdir="$c" && break
    done
fi

HELPER="$osdir/files/system/libexec/apex-firewall"
CAT="$osdir/files/system/firewall/services"
if [ ! -r "$HELPER" ] || [ ! -r "$CAT" ]; then
    echo "FATAL: no apex-os checkout with files/system/libexec/apex-firewall." >&2
    echo "       Pass one as an argument or set APEX_OS." >&2
    exit 2
fi
osdir="$(cd "$osdir" && pwd)"
HELPER="$osdir/files/system/libexec/apex-firewall"
CAT="$osdir/files/system/firewall/services"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/bin" "$WORK/conf" "$WORK/min" "$WORK/out"

# The copy, and the assertion that the redirect took.
sed -e "s#^readonly CONF_DIR=.*#readonly CONF_DIR=$WORK/conf#" \
    -e "s#^readonly CATALOGUE=.*#readonly CATALOGUE=$CAT#" \
    "$HELPER" > "$WORK/fw"
grep -q "^readonly CONF_DIR=$WORK/conf\$" "$WORK/fw" || {
    echo "FATAL: the CONF_DIR redirect did not apply. Every fixture below would" >&2
    echo "       have been a capture of the LIVE machine's /etc/apex/firewall.d." >&2
    exit 1
}
grep -q "^readonly CATALOGUE=$CAT\$" "$WORK/fw" || {
    echo "FATAL: the CATALOGUE redirect did not apply, so the catalogue would have been" >&2
    echo "       captured from the helper's built-in fallback rather than from the" >&2
    echo "       file the image ships." >&2
    exit 1
}

# `absent` has to mean nft is on NO path. With /usr/bin still on PATH an
# earlier version of this idea found the real nft and captured `unreadable`
# under the name `absent` — a fixture asserting the wrong state.
for c in bash basename sed tr grep paste cat id; do
    src="$(command -v "$c" 2>/dev/null)" && ln -sf "$src" "$WORK/min/$c"
done

nft_shim() {  # $1 = loaded|notloaded|unreadable|absent, $2 = set body when loaded
    case "$1" in
        loaded)     printf '#!/bin/bash\ncase "$*" in\n  "list table inet apex") echo ok; exit 0;;\n  "list set inet apex hotspot_ifaces") printf %%s "%s"; exit 0;;\nesac\nexit 0\n' "$2" > "$WORK/bin/nft"
                    chmod +x "$WORK/bin/nft" ;;
        notloaded)  printf '#!/bin/bash\necho "Error: No such file or directory" >&2\nexit 1\n' > "$WORK/bin/nft"
                    chmod +x "$WORK/bin/nft" ;;
        unreadable) printf '#!/bin/bash\necho "Error: Operation not permitted" >&2\nexit 1\n' > "$WORK/bin/nft"
                    chmod +x "$WORK/bin/nft" ;;
        absent)     rm -f "$WORK/bin/nft" ;;
    esac
}

exceptions() {  # each arg: name=spec
    rm -f "$WORK"/conf/*.conf 2>/dev/null
    local e
    for e in "$@"; do printf '%s\n' "${e#*=}" > "$WORK/conf/${e%%=*}.conf"; done
}

run() {  # $1 = absent|shim, rest = args
    local mode="$1"; shift
    if [ "$mode" = absent ]; then PATH="$WORK/min" bash "$WORK/fw" "$@" 2>/dev/null
    else                          PATH="$WORK/bin:$PATH" bash "$WORK/fw" "$@" 2>/dev/null
    fi
}

capture() {  # $1 = fixture name, $2 = absent|shim
    run "$2" status        > "$WORK/out/$1.txt"
    run "$2" status --json > "$WORK/out/$1.json"
}

# ── the six policy states, each with the exception list that makes it say the
#    most. `broken` is a file whose first line is not a valid spec: the reload
#    refuses it, and "that port is open" about a port that is closed is the one
#    answer this surface must never give. ────────────────────────────────────
nft_shim unreadable;  exceptions;                                             capture unreadable-none   shim
nft_shim unreadable;  exceptions broken='tcp notaport' mdns='udp 5353' syncthing='tcp 22000'
                                                                              capture unreadable-mixed  shim
nft_shim loaded '';   exceptions;                                             capture loaded-none       shim
nft_shim loaded 'elements = { "apexhost",
             "wlan0" }'
                      exceptions mdns='udp 5353' broken='tcp notaport';       capture loaded-hotspot    shim
nft_shim notloaded;   exceptions mdns='udp 5353';                             capture notloaded         shim
nft_shim absent;      exceptions mdns='udp 5353';                             capture nft-absent        absent

# ── the catalogue ───────────────────────────────────────────────────────────
nft_shim unreadable
run shim list > "$WORK/out/list.txt"

# A capture that came back empty is not a fixture, it is a helper that did not
# run — and an empty fixture makes every check against it pass vacuously.
for f in "$WORK"/out/*; do
    [ -s "$f" ] || { echo "FATAL: $(basename "$f") captured EMPTY" >&2; exit 1; }
done
# `unreadable-none` must actually say unreadable. If the shim were not on PATH
# the real nft would answer and every state above would be miscaptured under
# the wrong name.
grep -q '"policy": "unreadable"' "$WORK/out/unreadable-none.json" || {
    echo "FATAL: the nft shim was not the nft that answered." >&2; exit 1; }

if [ "$check" -eq 1 ]; then
    rc=0
    for f in "$WORK"/out/*; do
        b="$(basename "$f")"
        if ! diff -u "$here/$b" "$f" > /dev/null 2>&1; then
            echo "DRIFTED: $b"
            diff -u "$here/$b" "$f" | sed 's/^/    /'
            rc=1
        fi
    done
    for f in "$here"/*.txt "$here"/*.json; do
        [ -e "$f" ] || continue
        [ -e "$WORK/out/$(basename "$f")" ] || { echo "ORPHAN: $(basename "$f") is no longer captured"; rc=1; }
    done
    [ "$rc" -eq 0 ] && echo "firewall fixtures: match the helper in $osdir"
    exit "$rc"
fi

cp "$WORK"/out/* "$here/"
printf 'captured from %s\n' "$osdir" 
( cd "$osdir" && git log -1 --format='  apex-firewall at %H  %ad' --date=short 2>/dev/null ) || true
for f in "$here"/*.txt "$here"/*.json; do
    [ -e "$f" ] && printf '  %s\n' "$(basename "$f")"
done
