import QtQuick
import "../../../"
import "../../../theme"
import "../"
import "../../../components/config"

// Config → Blueprint  (roadmap §10, "GUI editing without hand-editing TOML")
//
// The blueprint is the declarative statement of what this machine should be.
// This page edits that file and nothing else.
//
// ── THE THREE THINGS THIS PAGE DOES NOT DO ───────────────────────────────────
//
// 1. It never authors TOML. Every value is read from `blueprint show --json`
//    and written back through `blueprint set --json -`, which puts it through
//    the same parser and atomic write a hand-edited file goes through. The TOML
//    shown at the bottom is the CLI rendering the SAVED file — it is display
//    only, and there is deliberately no preview of unsaved state, because
//    rendering a draft would mean implementing the schema twice.
//
// 2. It never applies on edit. Editing stages a draft in memory; Save writes
//    the file; Apply converges the machine. Three separate actions, in that
//    order, each behind its own button and none behind a timer. The declarative
//    model is worth nothing if the file is applied the instant it is touched.
//
// 3. It never escalates. Root-domain changes are shown as a line of text naming
//    `sudo apex apply`. There is no button next to it. `apex apply` converges
//    the privilege domain it is already in and reports the other, which is why
//    it cannot raise an authentication prompt at all — a button here that ran
//    sudo would throw that away.
//
// It also only ever writes the USER-owned file. The applied-state record under
// ~/.local/state is generated by `apex apply` and is not reachable from this
// page: if the editor could write it, `diff` would start agreeing with `apply`
// by construction instead of by measurement.
CfgScroll {
    id: root

    Component.onCompleted: BlueprintService.compare()

    // ── The CLI is not on this image ──────────────────────────────────────────
    // First and alone: with no `apex blueprint`, every other section would be an
    // empty editor for a file nobody can read. An explanation beats a blank page.
    CfgSection {
        title: "Blueprint"
        first: true
        visible: BlueprintService.loaded && !BlueprintService.available

        CfgRow {
            label: "Not available on this image"
            description: BlueprintService.unavailableReason
            hoverable: false
        }
        // The one control that must exist in this state. Everything else on the
        // page is hidden while `available` is false, so without a Try again
        // here the page is a dead end — and the state is reachable from a
        // freshly installed CLI that simply was not on PATH when the shell
        // started.
        CfgRow {
            label: "Try again"
            description: "Re-runs `apex blueprint show`"
            CfgButton {
                label: "Retry"
                onClicked: BlueprintService.refresh()
            }
        }
    }

    // ── Where this blueprint comes from ───────────────────────────────────────
    // Said before the first Save, not after it. `set` writes the user's own file
    // unconditionally, so saving while the site default is loaded forks it — and
    // from then on the administrator's changes stop arriving.
    CfgSection {
        title: "This file"
        first: !(BlueprintService.loaded && !BlueprintService.available)
        visible: BlueprintService.available

        CfgRow {
            label: BlueprintService.source === ""
                ? "No blueprint on this machine yet"
                : BlueprintService.source
            description: BlueprintService.saveNotice
            hoverable: false
        }
        CfgRow {
            label: "Generated state"
            description: (BlueprintService.paths.applied_state || "~/.local/state/apex/blueprint-state.toml") +
                         " — written by apex apply, never by this page. " +
                         "Keeping the two apart is what stops diff agreeing " +
                         "with apply by construction."
            hoverable: false
        }
        CfgRow {
            label: "Reload from disk"
            description: "The blueprint is a normal file and can be edited by hand"
            CfgButton {
                label: "Reload"
                onClicked: BlueprintService.refresh()
            }
        }
    }

    // ── Read errors ───────────────────────────────────────────────────────────
    CfgSection {
        title: "Problem"
        visible: BlueprintService.available && BlueprintService.lastError !== ""

        CfgRow {
            label: "Could not read the blueprint"
            description: BlueprintService.lastError
            hoverable: false
        }
    }

    // ── [desktop] ─────────────────────────────────────────────────────────────
    // "Not managed" is a real, distinct choice everywhere on this page: an
    // absent section means APEX does not manage that thing, NOT that it should
    // be set to a default. A blueprint that asserted defaults for everything it
    // did not mention would reformat a machine the first time it ran.
    CfgSection {
        title: "Desktop"
        visible: BlueprintService.available && BlueprintService.draft !== null

        CfgRow {
            label: "Compositor"
            description: "Which session the greeter selects. Applying this does " +
                         "not log you out."
            CfgSegmented {
                options: [{ value: "", label: "Not managed" }]
                    .concat(BlueprintService.compositors.map(c => ({ value: c, label: c })))
                value: BlueprintService.fieldOf("desktop", "compositor")
                onSelected: function(v) { BlueprintService.stage("desktop", "compositor", v) }
            }
        }
        CfgRow {
            label: "Colour scheme"
            description: "The matugen scheme derived from the wallpaper"
            CfgSegmented {
                options: [{ value: "", label: "Not managed" }]
                    .concat(BlueprintService.themes.map(t => ({ value: t, label: t })))
                value: BlueprintService.fieldOf("desktop", "theme")
                onSelected: function(v) { BlueprintService.stage("desktop", "theme", v) }
            }
        }
    }

    // ── [agent] ───────────────────────────────────────────────────────────────
    CfgSection {
        title: "Agent"
        visible: BlueprintService.available && BlueprintService.draft !== null

        CfgRow {
            label: "Default agent"
            CfgSegmented {
                options: [{ value: "", label: "Not managed" }]
                    .concat(BlueprintService.agents.map(a => ({ value: a, label: a })))
                value: BlueprintService.fieldOf("agent", "default")
                onSelected: function(v) { BlueprintService.stage("agent", "default", v) }
            }
        }
        CfgRow {
            label: "Sandbox policy"
            CfgSegmented {
                options: [{ value: "", label: "Not managed" }]
                    .concat(BlueprintService.sandboxes.map(s => ({ value: s, label: s })))
                value: BlueprintService.fieldOf("agent", "sandbox")
                onSelected: function(v) { BlueprintService.stage("agent", "sandbox", v) }
            }
        }
    }

    // ── [apps] ────────────────────────────────────────────────────────────────
    // Free text, because the vocabulary is every package name and Flatpak id in
    // existence. The CLI validates it; this page does not try to, and shows the
    // CLI's refusal verbatim if it comes.
    CfgSection {
        title: "Apps to install"
        visible: BlueprintService.available && BlueprintService.draft !== null

        CfgRow {
            label: "Add"
            description: "Repository package names and Flatpak application ids, " +
                         "classified the same way `apex install` classifies its " +
                         "arguments. A local .rpm is refused: a blueprint has to " +
                         "reproduce on another machine."
            CfgTextField {
                id: appField
                placeholder: "firefox or md.obsidian.Obsidian"
                onAccepted: function(t) {
                    BlueprintService.addItem("apps", "install", t)
                    appField.text = ""
                }
            }
        }

        Repeater {
            model: BlueprintService.listOf("apps", "install")

            delegate: CfgRow {
                required property var modelData
                label: String(modelData)
                CfgButton {
                    label: "Remove"
                    variant: "danger"
                    onClicked: BlueprintService.removeItem("apps", "install", modelData)
                }
            }
        }

        CfgRow {
            label: "Nothing listed"
            description: "APEX does not manage which apps are installed"
            hoverable: false
            visible: BlueprintService.listOf("apps", "install").length === 0
        }
    }

    // ── [development] ─────────────────────────────────────────────────────────
    CfgSection {
        title: "Languages"
        visible: BlueprintService.available && BlueprintService.draft !== null

        CfgRow {
            label: "Recorded and diffed, not installed"
            description: "Toolchain installation belongs to `apex env` capsules. " +
                         "Until then apply reports this section rather than " +
                         "guessing at a toolchain."
            hoverable: false
        }

        Repeater {
            model: BlueprintService.languages

            delegate: CfgRow {
                required property var modelData
                readonly property bool on:
                    BlueprintService.listOf("development", "languages").indexOf(modelData) >= 0
                label: String(modelData)
                CfgSwitch {
                    checked: on
                    onToggled: function(v) {
                        if (v) BlueprintService.addItem("development", "languages", modelData)
                        else   BlueprintService.removeItem("development", "languages", modelData)
                    }
                }
            }
        }
    }

    // ── [gaming] ──────────────────────────────────────────────────────────────
    CfgSection {
        title: "Gaming"
        visible: BlueprintService.available && BlueprintService.draft !== null

        CfgRow {
            label: "Observed and reported, never converged"
            description: "A Gaming machine is an image, not a package set. No " +
                         "command turns Daily into Gaming, so this is diffed and " +
                         "reported rather than applied."
            hoverable: false
        }
        CfgRow {
            label: "Expect a gaming edition"
            CfgSegmented {
                options: [{ value: "", label: "Not managed" },
                          { value: "yes", label: "yes" },
                          { value: "no",  label: "no" }]
                value: {
                    const v = BlueprintService.fieldOf("gaming", "enabled")
                    if (v === "") return ""
                    return v ? "yes" : "no"
                }
                onSelected: function(v) {
                    // "" clears the key entirely; false is a value, not a clear,
                    // so it cannot go through the same path as "".
                    if (v === "") BlueprintService.stage("gaming", "enabled", null)
                    else          BlueprintService.stage("gaming", "enabled", v === "yes")
                }
            }
        }
    }

    // ── Pending edits ─────────────────────────────────────────────────────────
    // A field-level list, deliberately, and not a rendered TOML preview: there
    // is no verb that renders an unsaved draft, and writing one here is the one
    // thing this page must not do.
    CfgSection {
        title: "Unsaved edits"
        visible: BlueprintService.available && BlueprintService.dirty

        Repeater {
            model: BlueprintService.pending

            delegate: CfgRow {
                required property var modelData
                label: modelData.what
                description: modelData.before + "  →  " + modelData.after
                hoverable: false
            }
        }

        CfgRow {
            label: "This would unmanage everything"
            description: "Saving an empty blueprint writes an empty file, which " +
                         "silently stops APEX managing anything it managed " +
                         "before. Nothing else on this page needs confirming."
            hoverable: false
            visible: BlueprintService.eraseWarning
        }

        CfgRow {
            label: BlueprintService.saving ? "Writing…" : "Save to the blueprint"
            description: "Writes the file. Changes the machine not at all — " +
                         "Apply is a separate action."
            CfgButton {
                label: BlueprintService.eraseWarning ? "Save anyway" : "Save"
                enabled: !BlueprintService.saving
                onClicked: BlueprintService.eraseWarning
                    ? BlueprintService.confirmErase()
                    : BlueprintService.save()
            }
        }
        CfgRow {
            label: "Discard"
            CfgButton {
                label: "Revert"
                variant: "danger"
                enabled: !BlueprintService.saving
                onClicked: BlueprintService.revert()
            }
        }
    }

    // ── Save result ───────────────────────────────────────────────────────────
    // The CLI's stderr, verbatim. An editor's rejection has to be identical to a
    // hand-edit's rejection; paraphrasing it here would make this page a second,
    // worse validator that drifts from the real one.
    CfgSection {
        title: "Save"
        visible: BlueprintService.available &&
                 (BlueprintService.saveError !== "" || BlueprintService.saveMessage !== "")

        CfgRow {
            label: "Refused"
            description: BlueprintService.saveError
            hoverable: false
            visible: BlueprintService.saveError !== ""
        }
        CfgRow {
            label: "Written"
            description: BlueprintService.saveMessage
            hoverable: false
            visible: BlueprintService.saveError === "" && BlueprintService.saveMessage !== ""
        }
    }

    // ── What this would change ────────────────────────────────────────────────
    CfgSection {
        title: "This machine vs the blueprint"
        visible: BlueprintService.available && BlueprintService.draft !== null

        CfgRow {
            label: BlueprintService.planning ? "Measuring…" : BlueprintService.planSummary
            description: BlueprintService.dirty
                ? "Measured against the SAVED file, not your unsaved edits."
                : "The machine is probed every time; there is no cached current state."
            hoverable: false
        }
        CfgRow {
            label: "Re-measure"
            CfgButton {
                label: "Compare"
                enabled: !BlueprintService.planning
                onClicked: BlueprintService.compare()
            }
            CfgButton {
                label: "Dry run"
                enabled: !BlueprintService.planning
                onClicked: BlueprintService.preview()
            }
        }

        Repeater {
            model: BlueprintService.plan ? BlueprintService.plan.user : []

            delegate: CfgRow {
                required property var modelData
                label: modelData.what
                description: modelData.current + "  →  " + modelData.desired +
                             "   ·   " + modelData.step
                hoverable: false
            }
        }

        Repeater {
            model: BlueprintService.plan ? BlueprintService.plan.unknown : []

            delegate: CfgRow {
                required property var modelData
                label: modelData.what + "  (unrecognised)"
                description: "This build does not know which privilege domain " +
                             "closes this gap: " + modelData.step
                hoverable: false
            }
        }
    }

    // ── Changes that need root ────────────────────────────────────────────────
    // Information. There is no button in this section, and that is the point.
    CfgSection {
        title: "Needs root"
        visible: BlueprintService.available && BlueprintService.rootNotice !== ""

        CfgRow {
            label: BlueprintService.rootNotice
            description: "Run it yourself in a terminal. `apex apply` converges " +
                         "only the privilege domain it is already running in and " +
                         "reports the other, which is why it never raises an " +
                         "authentication prompt. This page does not escalate."
            hoverable: false
        }

        Repeater {
            model: BlueprintService.plan ? BlueprintService.plan.root : []

            delegate: CfgRow {
                required property var modelData
                label: modelData.what
                description: modelData.current + "  →  " + modelData.desired +
                             "   ·   " + modelData.step
                hoverable: false
            }
        }
    }

    // ── Changes nobody can converge ───────────────────────────────────────────
    // Shown separately from convergence on purpose: a plan whose only changes
    // are blocked reports converged, so folding these into the summary would
    // hide exactly the rows that need explaining.
    CfgSection {
        title: "APEX cannot converge these"
        visible: BlueprintService.available && BlueprintService.plan !== null &&
                 BlueprintService.plan.blocked.length > 0

        Repeater {
            model: BlueprintService.plan ? BlueprintService.plan.blocked : []

            delegate: CfgRow {
                required property var modelData
                label: modelData.what
                description: modelData.current + "  →  " + modelData.desired +
                             "   ·   " + modelData.blocked
                hoverable: false
            }
        }
    }

    // ── Apply ─────────────────────────────────────────────────────────────────
    // The only section that changes the machine, behind the only button that
    // can, and reachable no other way. Nothing on this page calls apply() from a
    // timer, a binding or a save.
    CfgSection {
        title: "Apply"
        visible: BlueprintService.available && BlueprintService.draft !== null

        CfgRow {
            label: BlueprintService.applying ? "Applying…" : "Converge this machine"
            description: "Runs `apex apply` as you. Performs the changes in your " +
                         "own privilege domain and re-measures afterwards rather " +
                         "than trusting an exit code."
            CfgButton {
                label: "Apply"
                enabled: !BlueprintService.applying && !BlueprintService.dirty
                onClicked: BlueprintService.apply()
            }
        }
        CfgRow {
            label: "Save first"
            description: "Apply reads the file, not this page. Unsaved edits " +
                         "would not be part of it."
            hoverable: false
            visible: BlueprintService.dirty
        }
        CfgRow {
            label: "Failed"
            description: BlueprintService.applyError
            hoverable: false
            visible: BlueprintService.applyError !== ""
        }
        CfgRow {
            label: "Result"
            description: BlueprintService.applyOutput
            hoverable: false
            visible: BlueprintService.applyOutput !== ""
        }
    }

    // ── The saved file ────────────────────────────────────────────────────────
    // Rendered by the CLI, shown as text, never parsed and never edited here.
    CfgSection {
        title: "The file as saved"
        visible: BlueprintService.available && BlueprintService.toml !== ""

        Text {
            width: parent ? parent.width : 0
            text: BlueprintService.toml
            color: Theme.subtext
            font.family: "monospace"
            font.pixelSize: Theme.fs(10)
            wrapMode: Text.NoWrap
        }
    }
}
