#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  gen-lid-fixtures.sh — regenerate tests/fixtures/lid/*.json from the REAL
#  `apex lid` binary (roadmap P1-063).
#
#  Every fixture here is serde's own output, not JSON written from memory. That
#  matters more than usual for this page: `apex lid status --json` is nine
#  nested objects deep and six of them are internally-tagged enums, so a field
#  renamed on the apex-os side would leave a hand-written fixture agreeing with
#  a parser that no longer matches the machine — green suite, blank page.
#
#  Run it from an apex-os checkout, or point APEX_BIN at a built binary:
#
#      APEX_BIN=/path/to/apex-os/apexd/target/debug/apex \
#          tests/fixtures/lid/gen-lid-fixtures.sh
#
#  ── Which fixtures are real, and which cannot be ────────────────────────────
#
#  `APEX_LID_ROOT` re-roots every path the driver reads and makes it LOG rather
#  than run every external program, so under it `busctl` never answers and
#  `logind.docked` / `block_inhibited` come back null. That is exactly right
#  for a containment fixture and it means the undocked-and-acting case cannot
#  be produced this way. tests/lid-test.js therefore DERIVES that case by
#  editing `logind` on a real document rather than authoring a new one, so the
#  rest of the field names in it are still the machine's own.
#
#  The `status-docked.json` case is a capture of a real developer machine: an
#  L16 with an external display on card1-DP-1, which is why `acts_on_lid` is
#  false and why `policy_error` is present. Both are load-bearing — see the
#  header of src/services/lid.js.
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APEX="${APEX_BIN:-}"
if [ -z "$APEX" ]; then
    for c in apexd/target/debug/apex apexd/target/release/apex; do
        [ -x "$c" ] && APEX="$(cd "$(dirname "$c")" && pwd)/$(basename "$c")" && break
    done
fi
[ -n "$APEX" ] && [ -x "$APEX" ] || {
    echo "FATAL: no apex binary. Set APEX_BIN to one built from apex-os." >&2
    exit 2
}
command -v python3 >/dev/null 2>&1 || { echo "FATAL: python3 is required" >&2; exit 2; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

pretty() { python3 -m json.tool --sort-keys; }

# A fixture machine: a lid, a thermal zone with a declared critical trip, a
# battery, a panel backlight, a keyboard backlight. Same shape as apex-os's
# tests/test-apex-lid.sh, so the two suites describe one machine.
fx() {
    local F="$WORK/$1"; shift
    rm -rf "$F"
    mkdir -p "$F/proc/acpi/button/lid/LID" \
             "$F/sys/class/thermal/thermal_zone0" \
             "$F/sys/class/power_supply/BAT0" \
             "$F/sys/class/backlight/intel_backlight" \
             "$F/sys/class/leds/platform::kbd_backlight" \
             "$F/etc/apex" "$F/var/lib/apex/lid" "$F/home/nobody"
    echo open          > "$F/proc/acpi/button/lid/LID/state"
    echo x86_pkg_temp  > "$F/sys/class/thermal/thermal_zone0/type"
    echo 55000         > "$F/sys/class/thermal/thermal_zone0/temp"
    echo critical      > "$F/sys/class/thermal/thermal_zone0/trip_point_0_type"
    echo 100000        > "$F/sys/class/thermal/thermal_zone0/trip_point_0_temp"
    echo Battery       > "$F/sys/class/power_supply/BAT0/type"
    echo 80            > "$F/sys/class/power_supply/BAT0/capacity"
    echo Discharging   > "$F/sys/class/power_supply/BAT0/status"
    echo 700           > "$F/sys/class/backlight/intel_backlight/brightness"
    echo 0             > "$F/sys/class/backlight/intel_backlight/bl_power"
    echo 2             > "$F/sys/class/leds/platform::kbd_backlight/brightness"
    printf '%s\n' "$@" > "$F/etc/apex/lid.toml"
    printf '%s' "$F"
}

# HOME is pushed inside the fixture so the invoking account's own
# ~/.config/apex/lid.toml can never be read into a committed fixture.
drive() { local F="$1"; shift
    APEX_LID_ROOT="$F" HOME="$F/home/nobody" \
        XDG_CONFIG_HOME="$F/home/nobody/.config" "$APEX" lid "$@" 2>/dev/null; }

# ── 1. the real machine — CAPTURED ONLY ON REQUEST ──────────────────────────
# `status-l16-docked.json` is a capture of one real developer machine on one
# day: an L16 with an external display on card1-DP-1 and a root account holding
# a live /run/user/0. That is why `acts_on_lid` is false and why `policy_error`
# is present, and both of those are the point of the fixture.
#
# So it is NOT regenerated by default. Running this script on a machine with no
# external display, or with a pin set, would quietly replace the docked case
# with an undocked one and delete the only committed example of the two
# findings the page leads with. `--capture-real` overwrites it deliberately;
# without the flag the current machine is captured to a temp file and DIFFED,
# so a field renamed on the apex-os side is still reported here.
REAL="$here/status-l16-docked.json"
"$APEX" lid status --json | pretty > "$WORK/status-now.json"
if [ "${1:-}" = "--capture-real" ]; then
    cp "$WORK/status-now.json" "$REAL"
    echo "captured $(basename "$REAL") from this machine"
elif [ -f "$REAL" ]; then
    if python3 -c '
import json, sys
def keys(d, p=""):
    out = set()
    if isinstance(d, dict):
        for k, v in d.items():
            out.add(p + "/" + k); out |= keys(v, p + "/" + k)
    elif isinstance(d, list):
        for v in d:
            out |= keys(v, p + "[]")
    return out
a = keys(json.load(open(sys.argv[1])))
b = keys(json.load(open(sys.argv[2])))
gone = sorted(a - b)
if gone:
    print("fields in the committed capture that this machine no longer emits:")
    for g in gone:
        print("   ", g)
    sys.exit(1)
' "$REAL" "$WORK/status-now.json"; then
        echo "status-l16-docked.json    kept; every field in it is still emitted"
    else
        echo "status-l16-docked.json    STALE — see above" >&2
    fi
fi

# ── 2. pinned on, lid open: keep-working ────────────────────────────────────
F="$(fx keep 'pin = "on"')"
drive "$F" status --json | pretty > "$here/status-keep-working.json"

# ── 3. hot, lid shut, work pinned live: a thermal guard ─────────────────────
# 99 °C against a 100 °C critical trip and a 15 °C headroom: the guard fires.
F="$(fx guard 'pin = "on"')"
echo closed > "$F/proc/acpi/button/lid/LID/state"
echo 99000  > "$F/sys/class/thermal/thermal_zone0/temp"
drive "$F" status --json | pretty > "$here/status-guard-thermal.json"

# ── 4. nearly flat, lid shut, work pinned live: a battery guard ─────────────
F="$(fx battery 'pin = "on"')"
echo closed      > "$F/proc/acpi/button/lid/LID/state"
echo 9           > "$F/sys/class/power_supply/BAT0/capacity"
echo Discharging > "$F/sys/class/power_supply/BAT0/status"
drive "$F" status --json | pretty > "$here/status-guard-battery.json"

# ── 5. a machine with no sensors at all ─────────────────────────────────────
# Every reader answers its own kind of nothing: no lid, no thermal zone, no
# battery. The page must render all three as separate sentences.
F="$(fx bare 'pin = "auto"')"
rm -rf "$F/sys/class/thermal" "$F/sys/class/power_supply" \
       "$F/proc/acpi/button/lid/LID"
drive "$F" status --json | pretty > "$here/status-bare.json"

# ── 6. a real closed period, written by a real run ──────────────────────────
# `watch --once` closes the lid, takes the (logged, not spawned) inhibitor,
# runs the power-down, and writes the record that `report` reads back.
F="$(fx period 'pin = "on"')"
echo closed > "$F/proc/acpi/button/lid/LID/state"
drive "$F" watch --once >/dev/null
drive "$F" report --json | pretty > "$here/report-period.json"

# ── 7. nothing has ever happened ────────────────────────────────────────────
F="$(fx noperiod 'pin = "auto"')"
drive "$F" report --json | pretty > "$here/report-empty.json"

echo
for f in "$here"/*.json; do
    printf '%-28s %6s bytes\n' "$(basename "$f")" "$(wc -c < "$f")"
done
